cpu 	8086
bits 	16

	section .boot
boot:		
	CLI				;DISABLE INTERRUPTS
	MOV	AH,0D5H 		;SET SF, CF, ZF, AND AF FLAGS ON
	SAHF
	;JNC	ERR01			;GO TO ERR ROUTINE IF CF NOT SET
	;JNZ	ERR01			;GO TO ERR ROUTINE IF ZF NOT SET
	;JNP	ERR01			;GO TO ERR ROUTINE IF PF NOT SET
	;JNS	ERR01			;GO TO ERR ROUTINE IF SF NOT SET
	LAHF				;LOAD FLAG IMAGE TO AH
	MOV	CL,5			;LOAD CNT REG WITH SHIFT CNT
	SHR	AH,CL			;SHIFT AF INTO CARRY BIT POS
	;JNC	ERR01			;SO TO ERR ROUTINE IF AF NOT SET
	MOV	AL,40H			;SET THE OF FLAG ON
	SHL	AL,1			;SETUP FOR TESTING
	;JNO	ERR01			;GO TO ERR ROUTINE IF OF NOT SET
	XOR	AH,AH			;SET AH = 0
	SAHF				;CLEAR SF, CF, ZF, AND PF
	;JC	ERR01			;GO TO ERR ROUTINE IF CF ON
	;JZ	ERR01			;GO TO ERR ROUTINE IF ZF ON
	;JS	ERR01			;GO TO ERR ROUTINE IF SF ON
	;JP	ERR01			;GO TO ERR ROUTINE IF PF ON
	LAHF				;LOAD FLAG IMAGE TO AH
	MOV	CL,5			;LOAD CNT REG WITH SHIFT CNT
	SHR	AH,CL			;SHIFT AH INTO CARRY BIT POS
	;JC	ERR01			;GO TO ERR ROUTINE IF ON
	SHL	AH,1			;CHECK THAT OF IS CLEAR
	;JO	ERR01			;GO TO ERR ROUTINE IF ON

	section .reset
reset:
	jmp		0xf000:0